name: Fastly
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yaml'
      - 'fastly.toml'
      - 'Cargo.*'
      - 'src'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasi
    - uses: Swatinem/rust-cache@v2
    - uses: fastly/compute-actions@v5
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
