name: Fastly

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/fastly.yaml'
      - 'fastly.toml'
      - 'Cargo.*'
      - 'src/**/*'

env:
  RUSTFLAGS: -Ctarget-feature=-reference-types

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-wasi
    - uses: Swatinem/rust-cache@v2
    - uses: fastly/compute-actions@v8
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
